### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by BramDevlaminck** [SELab-2/OSOC-2#131]
- [x] tag maken met release
- [x] deploy
- [x] hoog niveau documentatie
- [x] documentation comments (typedoc)
- [x] guide to deployment 
- [x] testing guide (run `npm run integrationTests`) this sadly runs all tests at the moment
