### ISSUE TITLE
fix: finish and polish the students page

### ISSUE THREAD

**Issue by Mouwrice** [SELab-2/OSOC-2#517]
The students page is not entirely finished and has some bugs that need fixing. This is primarily frontend work but there are also some backend issues that need to be resolved.

***Frontend:***
- [x] Make it possible to deselect a student #509 
- [x] Update the `EvalutationBar` as evaluation data is changed
- [x] Evaluations of another person are shown in the student overview
- [x] Update evaluations when making an evaluation
- [x] Better integration of the final decision

***Backend:***

- [x] Fix suggestion types #515 
- [x] Fix student evalutations #516
