### ISSUE TITLE
Project TODO

### ISSUE THREAD

**Issue by BramDevlaminck** [SELab-2/OSOC-2#681]
- [x] notification when delete succeeds or fails
- [x] what to do with the draft route?
- [x] websocket for delete
